version: "3"
services:
  frontend:
    image: ghcr.io/suptar21/projectii-frontend:master
    container_name: studart-frontend
    environment:
      - VUE_APP_REST_API=${VUE_APP_REST_API}
      - VUE_APP_PRODUCT_VARIABLE=${VUE_APP_PRODUCT_VARIABLE}
    env_file:
      - ./.env
    ports:
      - "8080:80"

networks:
  default:
    external:
      name: studart-database-network
