version: "3"
services:
  frontend:
    image: ghcr.io/integrated-int222-studart/front-end:dev
    container_name: studart-frontend
    ports:
      - "8080:80"

networks:
  default:
    external:
      name: studart-network
